version: '2'

x-dbenv:
  &dbenv
  DB_NAME: $DB_DATABASE
  DB_USER: $DB_USERNAME
  DB_PASS: $DB_PASSWORD
  DB_HOST: $DB_HOST
  DB_PORT: 5432

x-rabenv:
  &rabenv
  RABBIT_HOST: "ebitda_rabbit"
  RABBIT_PORT: 5672

services:
  php:
    container_name: ebitda_php
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - $NGINX_PUBLIC_PORT:80
    depends_on:
      - ebitda_db

  ebitda_db:
    container_name: ebitda_db
    image: "postgres:latest"
    ports:
      - $DB_PUBLIC_PORT:5432
    environment:
      <<: *dbenv
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
      PGDATA: "/data/postgres"

  rabbitmq:
      image: "rabbitmq:3-management"
      container_name: "ebitda_rabbit"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        RABBITMQ_DEFAULT_VHOST: "/"
      volumes:
        - "./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      ports:
        - $RABBITMQ_PUBLIC_PORT:5672
        - $RABBITMQ_UI_PUBLIC_PORT:15672

  pgadmin4:
    container_name: ebitda_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - $PGADMIN_PUBLIC_PORT:80
    depends_on:
      - ebitda_db

#  data-manager:
#    container_name: ebitda_data_manager
#    build: ./../ebitda-data-manager
##    image: ebitda-data-manager-img
#    restart: unless-stopped
#    environment:
#      <<: *dbenv
#      <<: *rabenv
#      PYTHONUNBUFFERED: 1
#    volumes:
#      - ./upload_files:/var/lib/data_folder
#      - ./web/upload_files:/var/lib/data_destination
#      - ./../ebitda-data-manager:/var/lib
#    depends_on:
#      - ebitda_db

#  anylogic-api:
#    container_name: ebitda_anylogic_api
#    # build: ./../ebitda-anylogic-api
#    image: ebitda_anylogic-api
#    # restart: unless-stopped
#    environment:
#      <<: *dbenv
#      <<: *rabenv
#      PYTHONUNBUFFERED: 1
#    volumes:
#      # - ./upload_files:/var/lib/data_folder
#      - ./../ebitda-anylogic-api:/var/lib
#    depends_on:
#      - ebitda_db

volumes:
  db-data: